import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppProviders from './providers';
import { type ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function AppLayout({
	children,
	configuration,
	worklogs
}: Readonly<{
	children: ReactNode;
	configuration: ReactNode;
	worklogs: ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="light">
			<body className={inter.className}>
				<AppProviders>
					{configuration}
					{worklogs}
				</AppProviders>
			</body>
		</html>
	);
}
